loading:
  batch_size: 32
  shuffle: true
data_sampling_scheme_refs:
  train:
    - {scheme_name: default}
    # - {scheme_name: rot_only_20deg_std, sampling_prob: 0.5}
  val:
    - {scheme_name: default}
    # - {scheme_name: rot_only_20deg_std, sampling_prob: 0.5}
