default_schemeset_opts:
  train:
    loading:
      # nbr_batches: 1
      nbr_batches: 32
      nbr_batches_prior: 128
      # batch_size: 6
      batch_size: 32
      shuffle: true
      coupled_ref_and_query_scheme_sampling: false
    visualization:
      save_imgs_interval: 1
      plot_signals_interval: 1
      # plot_signal_stats_interval: 1
      plot_signal_stats_interval: 5
      # save_imgs_interval: null
      # plot_signals_interval: null
      # plot_signal_stats_interval: null
    data:
      pushopt: false # if enabled, every sample will be paired with another sample at ground-truth, in order to push down the predicted optimum there.
      pushopt_prob: None
      # pushopt: true # if enabled, every sample will be paired with another sample at ground-truth, in order to push down the predicted optimum there.
      # pushopt_prob: 0.5
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
      nbr_occluders: 4 # Occluders for synthetic ref images
      # nbr_occluders: 0 # Occluders for synthetic ref images
  val:
    loading:
      # nbr_batches: 1
      nbr_batches: 5
      batch_size: 32
      shuffle: false
      coupled_ref_and_query_scheme_sampling: false
    visualization:
      save_imgs_interval: 1
      plot_signals_interval: 1
      plot_signal_stats_interval: 5
      # save_imgs_interval: null
      # plot_signals_interval: null
      # plot_signal_stats_interval: null
    data:
      pushopt: false # if enabled, every sample will be paired with another sample at ground-truth, in order to push down the predicted optimum there.
      pushopt_prob: None
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
      nbr_occluders: 4 # Occluders for synthetic ref images
      # nbr_occluders: 0 # Occluders for synthetic ref images
data_sampling_scheme_defs:
  train:
    train:
      # never_blackbg_ref
      ref_schemeset:
        # # LINEMOD
        # - {scheme_name: synth_voc, sampling_prob: 0.34}
        # - {scheme_name: real_unoccl_train_keepbg, sampling_prob: 0.33}
        # - {scheme_name: real_unoccl_train_voc, sampling_prob: 0.33}

        # OccludedLINEMOD
        - {scheme_name: synth_voc, sampling_prob: 0.34}
        - {scheme_name: real_unoccl_all_keepbg, sampling_prob: 0.33}
        - {scheme_name: real_unoccl_all_voc, sampling_prob: 0.33}

      query_schemeset:
        # - scheme_name: default
        # - scheme_name: 90deg_std_mild_transl_depth
        # - scheme_name: 90deg_std_mild_transl
        # - scheme_name: 90deg_std_mild_depth

        # - scheme_name: 20deg_std

        # - scheme_name: rot_only_5deg_std

        # - scheme_name: rot_only_20deg_std
        #   # override: {blur_opts: {apply_blur: false}}

        # # - scheme_name: rot_only_90deg_std
        # # - scheme_name: transl_10perc
        # - scheme_name: depth_1_1

        - scheme_name: default
          sampling_prob: 0.2
        - scheme_name: noperturb
          # sampling_prob: 0.2
          # sampling_prob: 0.15
          sampling_prob: 0.1
          tasks_punished: [avg_reproj_err] # Main point of this is to push down and get an easily optimized shape for avg_reproj_err. Other tasks could be included, but may be a risk of learning flat regions.
          # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset, rel_depth_error] # Exclude fine_rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
          # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset] # Exclude rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        - scheme_name: rot_only_90deg_std
          sampling_prob: 0.2
          tasks_punished: [avg_reproj_err]
        - scheme_name: transl_30perc
          sampling_prob: 0.2
          tasks_punished: [pixel_offset]
          # tasks_punished: [norm_pixel_offset, pixel_offset]
        # - scheme_name: depth_1_05
        #   tasks_punished: [fine_rel_depth_error]
        - scheme_name: depth_1_3
          # sampling_prob: 0.2
          # sampling_prob: 0.25
          sampling_prob: 0.3
          tasks_punished: [rel_depth_error]

        # - scheme_name: default
        #   # sampling_prob: 0.2
        # - scheme_name: noperturb
        #   # sampling_prob: 0.2
        # - scheme_name: rot_only_90deg_std
        #   # sampling_prob: 0.2
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   # sampling_prob: 0.2
        #   tasks_punished: [norm_pixel_offset, pixel_offset]
        # - scheme_name: depth_1_3
        #   # sampling_prob: 0.2
        #   tasks_punished: [rel_depth_error]



# # LINEMOD
#   val:
#     # real_unoccl_train_rot_only_5deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: rot_only_5deg_std
#     #   use_for_val_score: false
#     # real_unoccl_test_rot_only_5deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_test_keepbg
#     #   query_schemeset:
#     #     - scheme_name: rot_only_5deg_std
#     #   use_for_val_score: true
#     # synth_voc_rot_only_5deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: rot_only_5deg_std
#     #   use_for_val_score: true
# 
#     # real_unoccl_train_rot_only_20deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: rot_only_20deg_std
#     #   use_for_val_score: false
#     # real_unoccl_test_rot_only_20deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_test_keepbg
#     #   query_schemeset:
#     #     - scheme_name: rot_only_20deg_std
#     #   use_for_val_score: true
#     # synth_voc_rot_only_20deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: rot_only_20deg_std
#     #   use_for_val_score: false
# 
#     # real_unoccl_train_rot_only_90deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: rot_only_90deg_std
#     #   use_for_val_score: false
#     real_unoccl_test_rot_only_90deg_std:
#       ref_schemeset:
#         - scheme_name: real_unoccl_test_keepbg
#       query_schemeset:
#         - scheme_name: rot_only_90deg_std
#       use_for_val_score: true
#     # synth_voc_rot_only_90deg_std:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: rot_only_90deg_std
#     #   use_for_val_score: false
# 
#     # real_unoccl_train_transl_10perc:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: transl_10perc
#     #   use_for_val_score: false
#     # real_unoccl_test_transl_10perc:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_test_keepbg
#     #   query_schemeset:
#     #     - scheme_name: transl_10perc
#     #   use_for_val_score: true
#     # synth_voc_transl_10perc:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: transl_10perc
#     #   use_for_val_score: false
# 
#     # real_unoccl_train_transl_30perc:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: transl_30perc
#     #   use_for_val_score: false
#     real_unoccl_test_transl_30perc:
#       ref_schemeset:
#         - scheme_name: real_unoccl_test_keepbg
#       query_schemeset:
#         - scheme_name: transl_30perc
#       use_for_val_score: true
#     # synth_voc_transl_30perc:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: transl_30perc
#     #   use_for_val_score: false
# 
#     # real_unoccl_train_depth_1_1:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: depth_1_1
#     #   use_for_val_score: false
#     # real_unoccl_test_depth_1_1:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_test_keepbg
#     #   query_schemeset:
#     #     - scheme_name: depth_1_1
#     #   use_for_val_score: true
#     # synth_voc_depth_1_1:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: depth_1_1
#     #   use_for_val_score: false
# 
#     # real_unoccl_train_depth_1_3:
#     #   ref_schemeset:
#     #     - scheme_name: real_unoccl_train_keepbg
#     #   query_schemeset:
#     #     - scheme_name: depth_1_3
#     #   use_for_val_score: false
#     real_unoccl_test_depth_1_3:
#       ref_schemeset:
#         - scheme_name: real_unoccl_test_keepbg
#       query_schemeset:
#         - scheme_name: depth_1_3
#       use_for_val_score: true
#     # synth_voc_depth_1_3:
#     #   ref_schemeset:
#     #     - scheme_name: synth_voc
#     #   query_schemeset:
#     #     - scheme_name: depth_1_3
#     #   use_for_val_score: false




# OccludedLINEMOD
  val:
    # real_unoccl_all_rot_only_5deg_std:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: rot_only_5deg_std
    #   use_for_val_score: false
    # real_occl_val_rot_only_5deg_std:
    #   ref_schemeset:
    #     - scheme_name: real_occl_val_keepbg
    #   query_schemeset:
    #     - scheme_name: rot_only_5deg_std
    #   use_for_val_score: true
    # synth_voc_rot_only_5deg_std:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: rot_only_5deg_std
    #   use_for_val_score: true

    # real_unoccl_all_rot_only_20deg_std:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: rot_only_20deg_std
    #   use_for_val_score: false
    # real_occl_val_rot_only_20deg_std:
    #   ref_schemeset:
    #     - scheme_name: real_occl_val_keepbg
    #   query_schemeset:
    #     - scheme_name: rot_only_20deg_std
    #   use_for_val_score: true
    # synth_voc_rot_only_20deg_std:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: rot_only_20deg_std
    #   use_for_val_score: false

    # real_unoccl_all_rot_only_90deg_std:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: rot_only_90deg_std
    #   use_for_val_score: false
    real_occl_val_rot_only_90deg_std:
      ref_schemeset:
        - scheme_name: real_occl_val_keepbg
      query_schemeset:
        - scheme_name: rot_only_90deg_std
      use_for_val_score: true
    # synth_voc_rot_only_90deg_std:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: rot_only_90deg_std
    #   use_for_val_score: false

    # real_unoccl_all_transl_10perc:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: transl_10perc
    #   use_for_val_score: false
    # real_occl_val_transl_10perc:
    #   ref_schemeset:
    #     - scheme_name: real_occl_val_keepbg
    #   query_schemeset:
    #     - scheme_name: transl_10perc
    #   use_for_val_score: true
    # synth_voc_transl_10perc:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: transl_10perc
    #   use_for_val_score: false

    # real_unoccl_all_transl_30perc:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: transl_30perc
    #   use_for_val_score: false
    real_occl_val_transl_30perc:
      ref_schemeset:
        - scheme_name: real_occl_val_keepbg
      query_schemeset:
        - scheme_name: transl_30perc
      use_for_val_score: true
    # synth_voc_transl_30perc:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: transl_30perc
    #   use_for_val_score: false

    # real_unoccl_all_depth_1_1:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: depth_1_1
    #   use_for_val_score: false
    # real_occl_val_depth_1_1:
    #   ref_schemeset:
    #     - scheme_name: real_occl_val_keepbg
    #   query_schemeset:
    #     - scheme_name: depth_1_1
    #   use_for_val_score: true
    # synth_voc_depth_1_1:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: depth_1_1
    #   use_for_val_score: false

    # real_unoccl_all_depth_1_3:
    #   ref_schemeset:
    #     - scheme_name: real_unoccl_all_keepbg
    #   query_schemeset:
    #     - scheme_name: depth_1_3
    #   use_for_val_score: false
    real_occl_val_depth_1_3:
      ref_schemeset:
        - scheme_name: real_occl_val_keepbg
      query_schemeset:
        - scheme_name: depth_1_3
      use_for_val_score: true
    # synth_voc_depth_1_3:
    #   ref_schemeset:
    #     - scheme_name: synth_voc
    #   query_schemeset:
    #     - scheme_name: depth_1_3
    #   use_for_val_score: false
