loading:
  batch_size: 32
  shuffle: true
data_sampling_scheme_refs:
  train:
    train:
      - {scheme_name: default}
      # - {scheme_name: rot_only_20deg_std, sampling_prob: 0.5}
  val:
    default:
      - {scheme_name: default}
    rot_only_20deg_std:
      - {scheme_name: rot_only_20deg_std}
    rot_only_20deg_std_quantile:
      - {scheme_name: rot_only_20deg_std_quantile}
