loading:
  batch_size: 32
  shuffle: true
data_sampling_scheme_refs:
  train:
    train:
      - {scheme_name: synth_default}
      # - {scheme_name: synth_rot_only_20deg_std, sampling_prob: 0.5}
  val:
    synth_default:
      - {scheme_name: synth_default}
    synth_rot_only_20deg_std:
      - {scheme_name: synth_rot_only_20deg_std}
    synth_rot_only_20deg_std_quantile:
      - {scheme_name: synth_rot_only_20deg_std_quantile}
