default_schemeset_opts:
  test:
    loading:
      nbr_batches: 3
      # batch_size: 1
      # batch_size: 2
      # batch_size: 3
      # batch_size: 6
      # batch_size: 7
      batch_size: 10
      # batch_size: 32
      shuffle: fixed
      # shuffle: true
      # shuffle: false
      coupled_ref_and_query_scheme_sampling: false
    poseopt:
      enabled: false
    visualization:
      save_imgs: true
      plot_signals: false
      plot_signal_stats: false
    data:
      pushopt: false
      pushopt_prob: None
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
      nbr_occluders: 4 # Occluders for synthetic ref images
      # nbr_occluders: 0 # Occluders for synthetic ref images
      crop_perturb:
        enable: false
        # enable: true
        # max_resize_factor: 1.3
        # max_rel_shift_factor: 0.3
data_sampling_scheme_defs:
  test:

    real_occl_test_keepbg_frame109_posesearch:
      ref_schemeset:
        - {scheme_name: real_occl_test_keepbg}
        # - {scheme_name: real_unoccl_train_keepbg_frame100}
        # - {scheme_name: real_occl_test_keepbg_frame30}
        # - {scheme_name: real_occl_test_keepbg_frame109}
        # - {scheme_name: real_occl_test_keepbg_frame112}
        # - {scheme_name: real_occl_test_keepbg_frame159}
        # - {scheme_name: real_occl_test_keepbg_frame649}
      query_schemeset: # NOTE: should ideally be disabled / not required during pose search
        # - scheme_name: 20deg_std
        - scheme_name: mild_gradual_rot
          # override: {background: from_ref}
      opts:
        poseopt:
          enabled: true

# # ==============================================================================
# # SIGNAL STATS
# # real_unoccl_train
# # ==============================================================================
#     # real_unoccl_train_keepbg_rot_only_5deg_std:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_train_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: rot_only_5deg_std
#     #       # override: {background: from_ref}
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     # real_unoccl_train_keepbg_rot_only_20deg_std:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_train_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: rot_only_20deg_std
#     #       # override: {background: from_ref}
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     # real_unoccl_train_keepbg_transl_10perc:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_train_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: transl_10perc
#     #       # override: {background: from_ref}
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     # real_unoccl_train_keepbg_depth_1_1:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_train_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: depth_1_1
#     #       # override: {background: from_ref}
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
# 
# # ==============================================================================
# # SIGNAL STATS
# # real_occl_val
# # ==============================================================================
#     real_occl_val_keepbg_rot_only_5deg_std:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: rot_only_5deg_std
#           # override: {background: from_ref}
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     real_occl_val_keepbg_rot_only_20deg_std:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: rot_only_20deg_std
#           # override: {background: from_ref}
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     real_occl_val_keepbg_transl_10perc:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: transl_10perc
#           # override: {background: from_ref}
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     real_occl_val_keepbg_depth_1_1:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: depth_1_1
#           # override: {background: from_ref}
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
# 
# 
# 
# 
# 
# 
# # ==============================================================================
# # real_unoccl_train_keepbg FRAME 100
# # ==============================================================================
#     real_unoccl_train_keepbg_frame100_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_unoccl_train_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#           # override: {background: from_ref}
#     real_unoccl_train_keepbg_frame100_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_unoccl_train_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_transl
#           # override: {background: from_ref}
#     real_unoccl_train_keepbg_frame100_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_unoccl_train_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_depth
#           # override: {background: from_ref}
# 
# 
# 
# # ==============================================================================
# # real_occl_val_keepbg FRAME 100
# # ==============================================================================
#     real_occl_val_keepbg_frame100_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#           # override: {background: from_ref}
#     real_occl_val_keepbg_frame100_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_transl
#           # override: {background: from_ref}
#     real_occl_val_keepbg_frame100_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_depth
#           # override: {background: from_ref}
# 
# 
# 
# # ==============================================================================
# # real_occl_test_keepbg FRAME 109
# # ==============================================================================
#     real_occl_test_keepbg_frame109_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame109}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#           # override: {background: from_ref}
#     real_occl_test_keepbg_frame109_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame109}
#       query_schemeset:
#         - scheme_name: gradual_transl
#           # override: {background: from_ref}
#     real_occl_test_keepbg_frame109_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame109}
#       query_schemeset:
#         - scheme_name: gradual_depth
#           # override: {background: from_ref}
# 
# 
# # ==============================================================================
# # real_occl_test_keepbg FRAME 112
# # ==============================================================================
#     real_occl_test_keepbg_frame112_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame112}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#           # override: {background: from_ref}
#     real_occl_test_keepbg_frame112_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame112}
#       query_schemeset:
#         - scheme_name: gradual_transl
#           # override: {background: from_ref}
#     real_occl_test_keepbg_frame112_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame112}
#       query_schemeset:
#         - scheme_name: gradual_depth
#           # override: {background: from_ref}
# 
# 
# # ==============================================================================
# # real_occl_test_keepbg FRAME 159
# # ==============================================================================
#     real_occl_test_keepbg_frame159_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame159}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#           # override: {background: from_ref}
#     real_occl_test_keepbg_frame159_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame159}
#       query_schemeset:
#         - scheme_name: gradual_transl
#           # override: {background: from_ref}
#     real_occl_test_keepbg_frame159_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame159}
#       query_schemeset:
#         - scheme_name: gradual_depth
#           # override: {background: from_ref}
