loading:
  batch_size: 32
  # shuffle: fixed
  shuffle: false
data_sampling_scheme_refs:
  test:
    default:
      - {scheme_name: default}
    rot_only_20deg_std:
      - {scheme_name: rot_only_20deg_std}
    rot_only_20deg_std_quantile:
      - {scheme_name: rot_only_20deg_std_quantile}
