loading:
  nbr_batches_train: 32
  # nbr_batches_val: 1
  nbr_batches_val: 5
  nbr_batches_prior: 128
  batch_size: 32
  shuffle: true
visualization:
  save_imgs_interval: 1
  plot_signals_interval: 1
  plot_signal_stats_interval: 5
data:
  min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
  max_nbr_resamplings: 100
data_sampling_scheme_defs:
  train:
    train:
      ref_schemeset:
        - {ref_scheme: synth_default, sample_prob: 0.5}
        - {ref_scheme: real_unoccl_duck, sample_prob: 0.5}
        # - {ref_scheme: real_unoccl_duck}
      query_scheme: default
  val:
    real_unoccl_duck:
      ref_schemeset:
        - {ref_scheme: real_unoccl_duck}
      query_scheme: default
    real_occl_val:
      ref_schemeset:
        - {ref_scheme: real_occl_val}
      query_scheme: default
    synth_default:
      ref_schemeset:
        - {ref_scheme: synth_default}
      query_scheme: default
    synth_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: synth_default}
      query_scheme: rot_only_20deg_std
    synth_rot_only_20deg_std_quantile:
      ref_schemeset:
        - {ref_scheme: synth_default}
      query_scheme: rot_only_20deg_std_quantile
