loading:
  # nbr_batches_train: 1
  nbr_batches_train: 32
  # nbr_batches_val: 1
  nbr_batches_val: 5
  nbr_batches_prior: 128
  batch_size: 32
visualization:
  save_imgs_interval: 1
  plot_signals_interval: 1
  plot_signal_stats_interval: 5
  # save_imgs_interval: null
  # plot_signals_interval: null
  # plot_signal_stats_interval: null
data:
  min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
  max_nbr_resamplings: 100
data_sampling_scheme_defs:
  train:
    train:
      ref_schemeset:
        # - {ref_scheme: synth_nyud, sample_prob: 0.5}
        - {ref_scheme: synth_blackbg, sample_prob: 0.5}
        - {ref_scheme: real_unoccl_train_blackbg, sample_prob: 0.5}
        # - {ref_scheme: real_unoccl_train, sample_prob: 0.25}
        # - {ref_scheme: real_unoccl_train_nyud, sample_prob: 0.25}
      # query_scheme: default
      # query_scheme: 90deg_std_mild_transl_depth
      # query_scheme: 90deg_std_mild_transl
      # query_scheme: 90deg_std_mild_depth
      # query_scheme: 20deg_std
      query_scheme: rot_only_20deg_std
      # query_scheme: rot_only_90deg_std
      shuffle: true
  val:
    # real_unoccl_train_blackbg_default:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_train_blackbg}
    #   query_scheme: default
    #   shuffle: false
    #   use_for_val_score: false
    # real_occl_val_blackbg_default:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_blackbg}
    #   query_scheme: default
    #   shuffle: false
    #   use_for_val_score: true
    # synth_blackbg:
    #   ref_schemeset:
    #     - {ref_scheme: synth_blackbg}
    #   query_scheme: default
    #   shuffle: false
    #   use_for_val_score: false



    # real_unoccl_train_blackbg_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_train_blackbg}
    #   query_scheme: 20deg_std
    #   shuffle: false
    #   use_for_val_score: false
    # real_occl_val_blackbg_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_blackbg}
    #   query_scheme: 20deg_std
    #   shuffle: false
    #   use_for_val_score: true
    # synth_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: synth_blackbg}
    #   query_scheme: 20deg_std
    #   shuffle: false
    #   use_for_val_score: false



    real_unoccl_train_blackbg_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: real_unoccl_train_blackbg}
      query_scheme: rot_only_20deg_std
      shuffle: false
      use_for_val_score: false
    real_occl_val_blackbg_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: real_occl_val_blackbg}
      query_scheme: rot_only_20deg_std
      shuffle: false
      use_for_val_score: true
    synth_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: synth_blackbg}
      query_scheme: rot_only_20deg_std
      shuffle: false
      use_for_val_score: false



    # real_unoccl_train_blackbg_rot_only_90deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_train_blackbg}
    #   query_scheme: rot_only_90deg_std
    #   shuffle: false
    #   use_for_val_score: false
    # real_occl_val_blackbg_rot_only_90deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_blackbg}
    #   query_scheme: rot_only_90deg_std
    #   shuffle: false
    #   use_for_val_score: true
    # synth_rot_only_90deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: synth_blackbg}
    #   query_scheme: rot_only_90deg_std
    #   shuffle: false
    #   use_for_val_score: false
