default_schemeset_opts:
  test:
    # loading:
    #   # nbr_batches: 1
    #   # batch_size: 1
    #   nbr_batches: 3
    #   batch_size: 32
    #   # shuffle: fixed
    #   # shuffle: true
    #   shuffle: false
    #   coupled_ref_and_query_scheme_sampling: false
    # poseopt:
    #   enabled: false

    loading:
      nbr_batches: null # ignored
      # batch_size: 1
      batch_size: 10
      shuffle: fixed
      # shuffle: true
      # shuffle: false
      coupled_ref_and_query_scheme_sampling: false
    poseopt:
      enabled: true
      # OccludedLINEMOD
      # init_pose_suffix: _pvnet
      # init_pose_suffix: _pvnet_depthfix # 180 degree rotation around camera frame y-axis to ensure positive depth
      # LINEMOD
      init_pose_suffix: _posecnn

    visualization:
      save_imgs: true
      plot_signals: false
      plot_signal_stats: false
    data:
      pushopt: false
      pushopt_prob: None
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
      nbr_occluders: 4 # Occluders for synthetic ref images
      # nbr_occluders: 0 # Occluders for synthetic ref images
data_sampling_scheme_defs:
  test:
    # real_occl_val_keepbg_frame100_mild_gradual_rot:
    #   ref_schemeset:
    #     # - {scheme_name: synth_voc}
    #     - {scheme_name: real_occl_val_keepbg_frame100}
    #   query_schemeset:
    #     - scheme_name: mild_gradual_rot
    # real_occl_val_keepbg_frame100_mild_gradual_transl:
    #   ref_schemeset:
    #     # - {scheme_name: synth_voc}
    #     - {scheme_name: real_occl_val_keepbg_frame100}
    #   query_schemeset:
    #     - scheme_name: mild_gradual_transl
    # real_occl_val_keepbg_frame100_mild_gradual_depth:
    #   ref_schemeset:
    #     # - {scheme_name: synth_voc}
    #     - {scheme_name: real_occl_val_keepbg_frame100}
    #   query_schemeset:
    #     - scheme_name: mild_gradual_depth

    posesearch:
      ref_schemeset:
        # # OccludedLINEMOD
        # - {scheme_name: real_occl_test_keepbg}
        # LINEMOD
        - {scheme_name: real_unoccl_test_keepbg}

        # - {scheme_name: real_occl_test_keepbg_frame30}
        # - {scheme_name: real_occl_test_keepbg_frame109}
        # - {scheme_name: real_occl_test_keepbg_frame112}
        # - {scheme_name: real_occl_test_keepbg_frame159}
        # - {scheme_name: real_occl_test_keepbg_frame649}
        # - {scheme_name: real_occl_test_keepbg_frame845}


        # - {scheme_name: real_unoccl_all_keepbg}
        # - {scheme_name: real_unoccl_all_keepbg_frame100}

        # - {scheme_name: real_unoccl_test_keepbg_frame194}
        # - {scheme_name: real_unoccl_test_keepbg_frame331}
        # - {scheme_name: real_unoccl_test_keepbg_frame720}

        # - {scheme_name: synth_voc}

      query_schemeset: # NOTE: should ideally be disabled / not required during pose search
        # - scheme_name: 20deg_std
        - scheme_name: mild_gradual_rot
      opts:
        poseopt:
          enabled: true

# # ==============================================================================
# # SIGNAL STATS
# # real_unoccl_all
# # ==============================================================================
#     # real_unoccl_all_keepbg_rot_only_5deg_std:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_all_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: rot_only_5deg_std
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     # real_unoccl_all_keepbg_rot_only_20deg_std:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_all_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: rot_only_20deg_std
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     # real_unoccl_all_keepbg_transl_10perc:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_all_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: transl_10perc
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     # real_unoccl_all_keepbg_depth_1_1:
#     #   ref_schemeset:
#     #     - {scheme_name: real_unoccl_all_keepbg}
#     #   query_schemeset:
#     #     - scheme_name: depth_1_1
#     #   opts:
#     #     loading: {nbr_batches: 64}
#     #     visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
# 
# # ==============================================================================
# # SIGNAL STATS
# # real_occl_val
# # ==============================================================================
#     real_occl_val_keepbg_rot_only_5deg_std:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: rot_only_5deg_std
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     real_occl_val_keepbg_rot_only_20deg_std:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: rot_only_20deg_std
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     real_occl_val_keepbg_transl_10perc:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: transl_10perc
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
#     real_occl_val_keepbg_depth_1_1:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg}
#       query_schemeset:
#         - scheme_name: depth_1_1
#       opts:
#         loading: {nbr_batches: 64}
#         visualization: {save_imgs: false, plot_signals: true, plot_signal_stats: true}
# 
# 
# 
# 
# 
# 
# # ==============================================================================
# # real_unoccl_all_keepbg FRAME 100
# # ==============================================================================
#     real_unoccl_all_keepbg_frame100_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_unoccl_all_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#     real_unoccl_all_keepbg_frame100_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_unoccl_all_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_transl
#     real_unoccl_all_keepbg_frame100_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_unoccl_all_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_depth
# 
# 
# 
# # ==============================================================================
# # real_occl_val_keepbg FRAME 100
# # ==============================================================================
#     real_occl_val_keepbg_frame100_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#     real_occl_val_keepbg_frame100_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_transl
#     real_occl_val_keepbg_frame100_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_val_keepbg_frame100}
#       query_schemeset:
#         - scheme_name: gradual_depth
# 
# 
# 
# # ==============================================================================
# # real_occl_test_keepbg FRAME 109
# # ==============================================================================
#     real_occl_test_keepbg_frame109_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame109}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#     real_occl_test_keepbg_frame109_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame109}
#       query_schemeset:
#         - scheme_name: gradual_transl
#     real_occl_test_keepbg_frame109_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame109}
#       query_schemeset:
#         - scheme_name: gradual_depth
# 
# 
# # ==============================================================================
# # real_occl_test_keepbg FRAME 112
# # ==============================================================================
#     real_occl_test_keepbg_frame112_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame112}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#     real_occl_test_keepbg_frame112_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame112}
#       query_schemeset:
#         - scheme_name: gradual_transl
#     real_occl_test_keepbg_frame112_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame112}
#       query_schemeset:
#         - scheme_name: gradual_depth
# 
# 
# # ==============================================================================
# # real_occl_test_keepbg FRAME 159
# # ==============================================================================
#     real_occl_test_keepbg_frame159_mild_gradual_rot:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame159}
#       query_schemeset:
#         - scheme_name: mild_gradual_rot
#     real_occl_test_keepbg_frame159_gradual_transl:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame159}
#       query_schemeset:
#         - scheme_name: gradual_transl
#     real_occl_test_keepbg_frame159_gradual_depth:
#       ref_schemeset:
#         - {scheme_name: real_occl_test_keepbg_frame159}
#       query_schemeset:
#         - scheme_name: gradual_depth
