training:
  n_epochs: 100
  learning_rate: 0.0001
  weight_decay: null
  backup_epochs: false
tasks:
  pixel_offset:                 {n_out: 2,   loss_func: L1, loss_weight: 1.e-2,   activation: null, min: null, max: null, unit: px}
  rel_depth_error:              {n_out: 1,   loss_func: L1, loss_weight: 1.0,   activation: null, min: null, max: null, unit: log_factor}
  delta_angle_inplane:          {n_out: 1,   loss_func: L1, loss_weight: 1.0,   activation: null, min: null, max: null, unit: angle}
  delta_angle_total:            {n_out: 1,   loss_func: L1, loss_weight: 1.0,   activation: null, min: null, max: null, unit: angle}
  norm_pixel_offset:            {n_out: 1,   loss_func: L2, loss_weight: 1.e-2,   activation: sigmoid, min: 0.0, max: 50.0, unit: px}
  abs_delta_angle_inplane:      {n_out: 1,   loss_func: L2, loss_weight: 1.0,   activation: sigmoid, min: 0.0, max: 3.1416, unit: angle}
  abs_delta_angle_total:        {n_out: 1,   loss_func: L2, loss_weight: 1.0,   activation: sigmoid, min: 0.0, max: 3.1416, unit: angle}
  abs_delta_angle_paxis:        {n_out: 1,   loss_func: L2, loss_weight: 1.0,   activation: sigmoid, min: 0.0, max: 3.1416, unit: angle}
  cosdist_delta_angle_inplane:  {n_out: 1,   loss_func: L2, loss_weight: 1.0,   activation: sigmoid, min: 0.0, max: 2.0, unit: cosdist}
  cosdist_delta_angle_total:    {n_out: 1,   loss_func: L2, loss_weight: 1.0,   activation: sigmoid, min: 0.0, max: 2.0, unit: cosdist}
  cosdist_delta_angle_paxis:    {n_out: 1,   loss_func: L2, loss_weight: 1.0,   activation: sigmoid, min: 0.0, max: 2.0, unit: cosdist}
logging:
  avg_window_size: 25
model:
  cnn_layers:
    - {n_out: 16, kernel_size: 3, stride: 1, dilation: 1, merge: false}
    - {n_out: 16, kernel_size: 3, stride: 1, dilation: 1, merge: false}
    - {n_out: 32, kernel_size: 3, stride: 1, dilation: 1, merge: true}
    - {n_out: 32, kernel_size: 3, stride: 1, dilation: 1, merge: false}
    - {n_out: 64, kernel_size: 3, stride: 2, dilation: 1, merge: true}
    - {n_out: 64, kernel_size: 3, stride: 1, dilation: 1, merge: false}
    - {n_out: 96, kernel_size: 3, stride: 2, dilation: 1, merge: true}
    - {n_out: 96, kernel_size: 3, stride: 1, dilation: 1, merge: false}
    - {n_out: 128, kernel_size: 3, stride: 2, dilation: 1, merge: true}
    - {n_out: 128, kernel_size: 3, stride: 1, dilation: 1, merge: false}
    - {n_out: 192, kernel_size: 3, stride: 2, dilation: 1, merge: true}
  head_layers:
    - {n_out: 1024, dropout_factor: null, relu_flag: true}
    - {n_out: 1024, dropout_factor: null, relu_flag: true}
    - {dropout_factor: null, relu_flag: false}
data:
  dataformat: dummy
  path: /datasets/occluded-linemod-augmented
  img_dims: [480, 480]
  crop_dims: [128, 128]
loading:
  train:
    batch_size: 32
    num_workers: 6
    shuffle: true
  val:
    batch_size: 32
    num_workers: 6
    shuffle: true
