training:
  n_epochs: 75
  # learning_rate: 1.e-5
  # learning_rate: 1.77e-5 # 1e-4 / sqrt(32)
  learning_rate: 5.e-5
  # learning_rate: 1.e-4
  backup_epochs: false
  clamp_predictions: false
targets:
  # pixel_offset:                    {n_out: 2,   activation: null,      min: null, max: null, unit: px}
  rel_depth_error:                 {n_out: 1,   activation: null,      min: null, max: null, unit: log_factor}
  norm_pixel_offset:               {n_out: 1,   activation: null,      min: 0.0, max: 50.0, unit: px}
  # delta_angle_inplane_signed:      {n_out: 1,   activation: null,      min: null, max: null, unit: angle}
  # delta_angle_inplane_unsigned:    {n_out: 1,   activation: null,      min: 0.0, max: 3.1416, unit: angle}
  # delta_angle_paxis:               {n_out: 1,   activation: null,      min: 0.0, max: 3.1416, unit: angle}

  # delta_angle_total:               {n_out: 1,   activation: null,      min: 0.0, max: 1.5708, unit: angle}
  delta_angle_total:               {n_out: 1,   activation: null,      min: 0.0, max: 3.1416, unit: angle}
  # delta_angle_total:               {n_out: 1,   activation: square,    min: 0.0, max: 3.1416, unit: angle}
  # delta_angle_total:               {n_out: 1,   activation: abs,       min: 0.0, max: 3.1416, unit: angle}

  # delta_angle_inplane_cosdist:     {n_out: 1,   activation: null,      min: 0.0, max: 2.0, unit: cosdist}
  # delta_angle_paxis_cosdist:       {n_out: 1,   activation: null,      min: 0.0, max: 2.0, unit: cosdist}
  # delta_angle_total_cosdist:       {n_out: 1,   activation: null,      min: 0.0, max: 2.0, unit: cosdist}
tasks:
  # pixel_offset:                       {target: pixel_offset,                      loss_func: L1,   loss_weight: 1.e-2,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # rel_depth_error:                    {target: rel_depth_error,                   loss_func: L1,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # delta_angle_inplane:                {target: delta_angle_inplane_signed,        loss_func: L1,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # delta_angle_paxis:                  {target: delta_angle_paxis,                 loss_func: L1,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # delta_angle_total:                  {target: delta_angle_total,                 loss_func: L1,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # norm_pixel_offset:                  {target: norm_pixel_offset,                 loss_func: L2,   loss_weight: 1.e-2,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # delta_angle_inplane_unsigned_L2:    {target: delta_angle_inplane_unsigned,      loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_paxis_L2:               {target: delta_angle_paxis,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg

  # rel_depth_error:
  #   target: rel_depth_error
  #   loss_func: L2
  #   loss_weight: 1.0
  #   clamp_before_loss: false
  #   prior_loss: null
  #   loss_decay: null
  # norm_pixel_offset:
  #   target: norm_pixel_offset
  #   loss_func: L2
  #   loss_weight: 1.e-2
  #   clamp_before_loss: false
  #   prior_loss: null
  #   loss_decay:
  #     # - {method: relative, min_denominator: 0.5}
  #     # - {method: relative, min_denominator: 0.1}
  #     # - {method: relative, min_denominator: 0.05}
  #     - {method: relative, min_denominator: 0.01}
  delta_angle_total:
    target: delta_angle_total
    loss_func: L1
    # loss_func: L2
    loss_weight: 1.0
    clamp_before_loss: false
    prior_loss: null
    loss_decay: null
    # BELOW: deactivated loss decay based on other targets (in order not to train angle when too hard).
    # loss_decay:
    #   # - {method: relative, min_denominator: 0.005}
    # 
    #   # 0-20 px
    #   - {method: smoothstep, target: norm_pixel_offset, x1: 0.0, x2: 20.0, y1: 1.0, y2: 0.0}
    #   # 0-40 px
    #   # - {method: smoothstep, target: norm_pixel_offset, x1: 0.0, x2: 40.0, y1: 1.0, y2: 0.0}
    #   # 20-40 px
    #   # - {method: smoothstep, target: norm_pixel_offset, x1: 20.0, x2: 40.0, y1: 1.0, y2: 0.0}
    # 
    #   # 1.0-1.2
    #   - {method: smoothstep, target: rel_depth_error, x1: -0.079, x2: -0.0, y1: 0.0, y2: 1.0} # log(1.2)=0.079
    #   - {method: smoothstep, target: rel_depth_error, x1: 0.0, x2: 0.079, y1: 1.0, y2: 0.0} # log(1.2)=0.079
    #   # 1.0-1.5
    #   # - {method: smoothstep, target: rel_depth_error, x1: -0.176, x2: -0.0, y1: 0.0, y2: 1.0} # log(1.5)=0.176
    #   # - {method: smoothstep, target: rel_depth_error, x1: 0.0, x2: 0.176, y1: 1.0, y2: 0.0} # log(1.5)=0.176
    #   # 1.2-1.5
    #   # - {method: smoothstep, target: rel_depth_error, x1: -0.176, x2: -0.079, y1: 0.0, y2: 1.0} # log(1.2)=0.079, log(1.5)=0.176
    #   # - {method: smoothstep, target: rel_depth_error, x1: 0.079, x2: 0.176, y1: 1.0, y2: 0.0} # log(1.2)=0.079, log(1.5)=0.176

  # delta_angle_total_L2_decay3deg:             {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.05}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_L2_decay12deg:            {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_L2_relative006deg:        {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.001}]} # 0.06 deg
  # delta_angle_total_L2_relative03deg:         {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.005}]} # 0.3 deg
  # delta_angle_total_L2_relative06deg:         {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.01}]} # 0.6 deg
  # delta_angle_total_L2_relative6deg:          {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.1}]} # 6 deg
  # delta_angle_total_L2:                       {target: delta_angle_total,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # 
  # delta_angle_total_sq_L2_decay3deg:          {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.05}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_sq_L2_decay12deg:         {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_sq_L2_relative006deg:     {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.001}]} # 0.06 deg
  # delta_angle_total_sq_L2_relative03deg:      {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.005}]} # 0.3 deg
  # delta_angle_total_sq_L2_relative06deg:      {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.01}]} # 0.6 deg
  # delta_angle_total_sq_L2_relative6deg:       {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.1}]} # 6 deg
  # delta_angle_total_sq_L2:                    {target: delta_angle_total_sq,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # 
  # delta_angle_total_abs_L2_decay3deg:          {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.05}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_abs_L2_decay12deg:         {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_abs_L2_relative006deg:     {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.001}]} # 0.06 deg
  # delta_angle_total_abs_L2_relative03deg:      {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.005}]} # 0.3 deg
  # delta_angle_total_abs_L2_relative06deg:      {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.01}]} # 0.6 deg
  # delta_angle_total_abs_L2_relative6deg:       {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: [{method: relative, min_denominator: 0.1}]} # 6 deg
  # delta_angle_total_abs_L2:                    {target: delta_angle_total_abs,                 loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: null, loss_decay: null}
  # 
  # delta_angle_total_L2_sh_decay3deg:          {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: exp_decay, halflife: 0.05}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_L2_sh_decay12deg:         {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_L2_sh_relative006deg:     {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.001}]} # 0.06 deg
  # delta_angle_total_L2_sh_relative03deg:      {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.005}]} # 0.3 deg
  # delta_angle_total_L2_sh_relative06deg:      {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.01}]} # 0.6 deg
  # delta_angle_total_L2_sh_relative6deg:       {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.1}]} # 6 deg
  # delta_angle_total_L2_sh:                    {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: null}
  # 
  # delta_angle_total_sq_L2_sh_decay3deg:       {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: exp_decay, halflife: 0.05}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_sq_L2_sh_decay12deg:      {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_sq_L2_sh_relative006deg:  {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.001}]} # 0.06 deg
  # delta_angle_total_sq_L2_sh_relative03deg:   {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.005}]} # 0.3 deg
  # delta_angle_total_sq_L2_sh_relative06deg:   {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.01}]} # 0.6 deg
  # delta_angle_total_sq_L2_sh_relative6deg:    {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.1}]} # 6 deg
  # delta_angle_total_sq_L2_sh:                 {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: null}
  # 
  # delta_angle_total_abs_L2_sh_decay3deg:       {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: exp_decay, halflife: 0.05}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_abs_L2_sh_decay12deg:      {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: exp_decay, halflife: 0.2}]} # Decay by 0.5 after every "halflife" radians. 0.1 radians ~= 5.7deg
  # delta_angle_total_abs_L2_sh_relative006deg:  {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.001}]} # 0.06 deg
  # delta_angle_total_abs_L2_sh_relative03deg:   {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.005}]} # 0.3 deg
  # delta_angle_total_abs_L2_sh_relative06deg:   {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.01}]} # 0.6 deg
  # delta_angle_total_abs_L2_sh_relative6deg:    {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: [{method: relative, min_denominator: 0.1}]} # 6 deg
  # delta_angle_total_abs_L2_sh:                 {target: delta_angle_total,              loss_func: L2,   loss_weight: 1.0,   clamp_before_loss: false, prior_loss: {method: sinkhorn, loss_weight: 1.0}, loss_decay: null}
logging:
  avg_window_size: 25
model:
  architecture: custom_siamese
  custom_siamese_opts:
    # weight_decay: null
    weight_decay: {cnn: 0, head: 1.e-4}
    coord_maps:
      enabled: True
      viewing_ray_dependent_coordinates: True
      preserve_scale: False
      # NOTE: Different tasks might desire different format on coord maps. Maybe supply coord maps in multiple formats?
    # siamese_net: true
    siamese_net: false
    cnn_layers:
      - {n_out: 16, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: false}
      - {n_out: 16, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: false}
      - {n_out: 32, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: true}
      - {n_out: 32, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: false}
      - {n_out: 64, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: false, merge: true}
      - {n_out: 64, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: false}
      - {n_out: 96, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: false, merge: true}
      - {n_out: 96, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: false}
      - {n_out: 128, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: false, merge: true}
      - {n_out: 128, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: false, merge: false}
      - {n_out: 192, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: false, merge: true}
    # cnn_layers:
    #   - {n_out: 16, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: false}
    #   - {n_out: 16, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: false}
    #   - {n_out: 32, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: true}
    #   - {n_out: 32, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: false}
    #   - {n_out: 64, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: true, merge: true}
    #   - {n_out: 64, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: false}
    #   - {n_out: 96, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: true, merge: true}
    #   - {n_out: 96, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: false}
    #   - {n_out: 128, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: true, merge: true}
    #   - {n_out: 128, kernel_size: 3, stride: 1, dilation: 1, domain_specific_params: true, merge: false}
    #   - {n_out: 192, kernel_size: 3, stride: 2, dilation: 1, domain_specific_params: true, merge: true}
    head_layers:
      - {n_out: 1024, dropout_factor: 0.3, bias: true, relu_flag: true}
      - {n_out: 1024, dropout_factor: 0.3, bias: true, relu_flag: true}
      - {dropout_factor: null, bias: true, relu_flag: false}
      # - {dropout_factor: null, bias: false, relu_flag: false}
data:
  dataformat: dummy
  path: /datasets/occluded-linemod-augmented
  nyud_path: /datasets/nyud
  voc_path: /datasets/voc
  img_dims: [480, 480]
  crop_dims: [128, 128]
  ref_colorjitter_during_train: true
