default_schemeset_opts:
  train:
    loading:
      # nbr_batches: 1
      nbr_batches: 32
      nbr_batches_prior: 128
      batch_size: 32
      shuffle: true
    visualization:
      save_imgs_interval: 1
      plot_signals_interval: 1
      plot_signal_stats_interval: 5
      # save_imgs_interval: null
      # plot_signals_interval: null
      # plot_signal_stats_interval: null
    data:
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
  val:
    loading:
      # nbr_batches: 1
      nbr_batches: 5
      batch_size: 32
      shuffle: false
    visualization:
      save_imgs_interval: 1
      plot_signals_interval: 1
      plot_signal_stats_interval: 5
      # save_imgs_interval: null
      # plot_signals_interval: null
      # plot_signal_stats_interval: null
    data:
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
data_sampling_scheme_defs:
  train:
    train:
      # baseline
      ref_schemeset:
        - {ref_scheme: synth_blackbg, sample_prob: 0.5}
        - {ref_scheme: real_unoccl_train_blackbg, sample_prob: 0.5}
      
      # # synth_blackbg_real_mix
      # ref_schemeset:
      #   - {ref_scheme: synth_blackbg, sample_prob: 0.5}
      #   - {ref_scheme: real_unoccl_train_blackbg, sample_prob: 0.25}
      #   - {ref_scheme: real_unoccl_train, sample_prob: 0.125}
      #   - {ref_scheme: real_unoccl_train_nyud, sample_prob: 0.125}
      
      # # never_blackbg
      # ref_schemeset:
      #   - {ref_scheme: synth_nyud, sample_prob: 0.5}
      #   - {ref_scheme: real_unoccl_train, sample_prob: 0.25}
      #   - {ref_scheme: real_unoccl_train_nyud, sample_prob: 0.25}

      # # whitesilhouette
      # ref_schemeset:
      #   - {ref_scheme: synth_whitesilhouette, sample_prob: 0.5}
      #   - {ref_scheme: real_unoccl_train_whitesilhouette, sample_prob: 0.5}

      # query_scheme: default
      # query_scheme: 90deg_std_mild_transl_depth
      # query_scheme: 90deg_std_mild_transl
      # query_scheme: 90deg_std_mild_depth
      # query_scheme: 20deg_std
      query_scheme: rot_only_20deg_std
      # query_scheme: rot_only_90deg_std

  val:
    # real_unoccl_train_blackbg_default:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_train_blackbg}
    #   query_scheme: default
    #   use_for_val_score: false
    # real_occl_val_blackbg_default:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_blackbg}
    #   query_scheme: default
    #   use_for_val_score: true
    # synth_blackbg:
    #   ref_schemeset:
    #     - {ref_scheme: synth_blackbg}
    #   query_scheme: default
    #   use_for_val_score: false



    # real_unoccl_train_blackbg_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_train_blackbg}
    #   query_scheme: 20deg_std
    #   use_for_val_score: false
    # real_occl_val_blackbg_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_blackbg}
    #   query_scheme: 20deg_std
    #   use_for_val_score: true
    # synth_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: synth_blackbg}
    #   query_scheme: 20deg_std
    #   use_for_val_score: false



    real_unoccl_train_blackbg_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: real_unoccl_train_blackbg}
      query_scheme: rot_only_20deg_std
      use_for_val_score: false
    real_occl_val_blackbg_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: real_occl_val_blackbg}
      query_scheme: rot_only_20deg_std
      use_for_val_score: true
    synth_rot_only_20deg_std:
      ref_schemeset:
        - {ref_scheme: synth_blackbg}
      query_scheme: rot_only_20deg_std
      use_for_val_score: false



    # real_unoccl_train_blackbg_rot_only_90deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_train_blackbg}
    #   query_scheme: rot_only_90deg_std
    #   use_for_val_score: false
    # real_occl_val_blackbg_rot_only_90deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_blackbg}
    #   query_scheme: rot_only_90deg_std
    #   use_for_val_score: true
    # synth_rot_only_90deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: synth_blackbg}
    #   query_scheme: rot_only_90deg_std
    #   use_for_val_score: false
