default_schemeset_opts:
  train:
    loading:
      # nbr_batches: 1
      nbr_batches: 32
      nbr_batches_prior: 128
      # batch_size: 1
      # batch_size: 4
      # batch_size: 6
      # batch_size: 8
      # batch_size: 12
      batch_size: 16
      # batch_size: 32
      shuffle: true
      coupled_ref_and_query_scheme_sampling: false
    visualization:
      save_imgs_interval: 1
      plot_signals_interval: 1
      # plot_signal_stats_interval: 1
      plot_signal_stats_interval: 5
      # save_imgs_interval: null
      # plot_signals_interval: null
      # plot_signal_stats_interval: null
    data:
      pushopt: false # if enabled, every sample will be paired with another sample at ground-truth, in order to push down the predicted optimum there.
      pushopt_prob: None
      # pushopt: true # if enabled, every sample will be paired with another sample at ground-truth, in order to push down the predicted optimum there.
      # pushopt_prob: 0.5
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
  val:
    loading:
      # nbr_batches: 1
      nbr_batches: 5
      batch_size: 32
      shuffle: false
      coupled_ref_and_query_scheme_sampling: false
    visualization:
      save_imgs_interval: 1
      plot_signals_interval: 1
      plot_signal_stats_interval: 5
      # save_imgs_interval: null
      # plot_signals_interval: null
      # plot_signal_stats_interval: null
    data:
      pushopt: false # if enabled, every sample will be paired with another sample at ground-truth, in order to push down the predicted optimum there.
      pushopt_prob: None
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
data_sampling_scheme_defs:
  train:
    train:
      query_schemeset:
        # - scheme_name: default
        # - scheme_name: 90deg_std_mild_transl_depth
        # - scheme_name: 90deg_std_mild_transl
        # - scheme_name: 90deg_std_mild_depth

        # - scheme_name: 20deg_std

        # - scheme_name: rot_only_5deg_std

        # - scheme_name: rot_only_20deg_std
        #   # override: {blur_opts: {apply_blur: false}}

        # # - scheme_name: rot_only_90deg_std
        # # - scheme_name: transl_10perc
        # - scheme_name: depth_1_1




        # # reprojonly-depthonly1_005
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_005
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   loss_weight: 3.0



        # # reprojonly-depthonly1_02
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_02
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   loss_weight: 3.0



        # # reprojonly-depthonly1_05
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   loss_weight: 3.0



        # # deepim_perturb
        # - scheme_name: deepim


        # # deepim_perturb_sepdev
        # - scheme_name: deepim
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_20deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # deepim_perturb_sepdepth
        # - scheme_name: deepim
        #   sampling_prob: 0.5
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.5
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # deepim_perturb_sepdevonly_depth_1_05_lognorm_depthreg
        # - scheme_name: rot_only_20deg_std
        #   tasks_punished: [avg_reproj_err]
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   tasks_punished: [avg_reproj_err]
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   tasks_punished: [avg_reproj_err, rel_depth_error]
        #   sampling_prob: 0.4
        #   # loss_weight: 1.0
        #   loss_weight: 3.0

        # # deepim_perturb_sepdevonly_depth_1_05_lognorm
        # - scheme_name: rot_only_20deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.4
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # deepim_perturb_sepdevonly_depth_1_1_lognorm_rot45
        - scheme_name: rot_only_45deg_std
          sampling_prob: 0.3
          # loss_weight: 1.0
        - scheme_name: transl_10perc
          sampling_prob: 0.3
          # loss_weight: 1.0
        - scheme_name: depth_1_1
          sampling_prob: 0.4
          # loss_weight: 1.0
          loss_weight: 3.0


        # # deepim_perturb_sepdevonly_depth_1_05_lognorm_rot90
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.4
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # deepim_perturb_sepdevonly_depth_1_3_lognorm
        # - scheme_name: rot_only_20deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_3
        #   sampling_prob: 0.4
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # deepim_perturb_sepdevonly_depth_2_05_lognorm
        # - scheme_name: rot_only_20deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: depth_2_05
        #   sampling_prob: 0.4
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # deepim_perturb_sepdevonly_depth_1_05_gauss
        # - scheme_name: rot_only_20deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_10perc
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05_gauss
        #   sampling_prob: 0.4
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # noperturb
        # - scheme_name: noperturb


        # # reprojonly-depthonly1_15
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_15
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   loss_weight: 3.0


        # # reprojonly-depthonly_1_3
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_3
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   loss_weight: 3.0



        # # reprojonly-finedepth
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: noperturb
        #   sampling_prob: 0.1
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0



        # # reprojonly-finedepthonly
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0



        # # reprojonly-no_depthonly_sample
        # - scheme_name: default
        #   sampling_prob: 0.2857 # = 0.2 / 0.7
        #   # loss_weight: 1.0
        # - scheme_name: noperturb
        #   sampling_prob: 0.1429 # = 0.1 / 0.7
        #   # loss_weight: 1.0
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.2857 # = 0.2 / 0.7
        #   # loss_weight: 1.0
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2857 # = 0.2 / 0.7
        #   # loss_weight: 1.0



        # # reproj_and_fine_rel_depth_error
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: noperturb
        #   sampling_prob: 0.1
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   tasks_punished: [rel_depth_error]



        # # mix-depth_1_3
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        # - scheme_name: noperturb
        #   sampling_prob: 0.1
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err] # Main point of this is to push down and get an easily optimized shape for avg_reproj_err. Other tasks could be included, but may be a risk of learning flat regions.
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [pixel_offset]
        # - scheme_name: depth_1_3
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   tasks_punished: [rel_depth_error]



        # # mix-depth_1_05
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err, pixel_offset]
        # - scheme_name: noperturb
        #   sampling_prob: 0.1
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err] # Main point of this is to push down and get an easily optimized shape for avg_reproj_err. Other tasks could be included, but may be a risk of learning flat regions.
        #   # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset, rel_depth_error] # Exclude fine_rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        #   # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset] # Exclude rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [pixel_offset]
        # - scheme_name: depth_1_05
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   tasks_punished: [rel_depth_error]



        # # mix-depth_1_02
        # - scheme_name: default
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err, pixel_offset]
        # - scheme_name: noperturb
        #   sampling_prob: 0.1
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err] # Main point of this is to push down and get an easily optimized shape for avg_reproj_err. Other tasks could be included, but may be a risk of learning flat regions.
        #   # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset, rel_depth_error] # Exclude fine_rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        #   # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset] # Exclude rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        # - scheme_name: rot_only_90deg_std
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   sampling_prob: 0.2
        #   # loss_weight: 1.0
        #   tasks_punished: [pixel_offset]
        # - scheme_name: depth_1_02
        #   sampling_prob: 0.3
        #   # loss_weight: 1.0
        #   tasks_punished: [rel_depth_error]



        # # mix-nodepth
        # - scheme_name: default
        #   # sampling_prob: 0.2
        #   sampling_prob: 0.2857 # = 0.2 / 0.7
        #   # loss_weight: 1.0
        # - scheme_name: noperturb
        #   # sampling_prob: 0.1
        #   sampling_prob: 0.1429 # = 0.1 / 0.7
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err] # Main point of this is to push down and get an easily optimized shape for avg_reproj_err. Other tasks could be included, but may be a risk of learning flat regions.
        #   # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset, rel_depth_error] # Exclude fine_rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        #   # tasks_punished: [avg_reproj_err, norm_pixel_offset, pixel_offset] # Exclude rel_depth_error in order to avoid flat regions and thus increase precision close to optimum.
        # - scheme_name: rot_only_90deg_std
        #   # sampling_prob: 0.2
        #   sampling_prob: 0.2857 # = 0.2 / 0.7
        #   # loss_weight: 1.0
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   # sampling_prob: 0.2
        #   sampling_prob: 0.2857 # = 0.2 / 0.7
        #   # loss_weight: 1.0
        #   tasks_punished: [pixel_offset]




        # - scheme_name: default
        #   # sampling_prob: 0.2
        # - scheme_name: noperturb
        #   # sampling_prob: 0.2
        # - scheme_name: rot_only_90deg_std
        #   # sampling_prob: 0.2
        #   tasks_punished: [avg_reproj_err]
        # - scheme_name: transl_30perc
        #   # sampling_prob: 0.2
        #   tasks_punished: [norm_pixel_offset, pixel_offset]
        # - scheme_name: depth_1_3
        #   # sampling_prob: 0.2
        #   tasks_punished: [rel_depth_error]
