loading:
  nbr_batches_test: 3
  batch_size: 32
visualization:
  save_imgs: true
  plot_signals: false
  plot_signal_stats: false
data:
  min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
  max_nbr_resamplings: 100
data_sampling_scheme_defs:
  test:
    # real_unoccl_duck_default:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_duck}
    #   query_scheme: default
    #   shuffle: false
    #   visualization:
    #     save_imgs: true
    #     plot_signals: true
    #     plot_signal_stats: true
    # real_occl_val_default:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val}
    #   query_scheme: default
    #   shuffle: false
    #   visualization:
    #     save_imgs: true
    #     plot_signals: true
    #     plot_signal_stats: true
    # synth_default:
    #   ref_schemeset:
    #     - {ref_scheme: synth_default}
    #   query_scheme: default
    #   shuffle: false
    #   visualization:
    #     save_imgs: true
    #     plot_signals: true
    #     plot_signal_stats: true
    # synth_rot_only_20deg_std:
    #   ref_schemeset:
    #     - {ref_scheme: synth_default}
    #   query_scheme: rot_only_20deg_std
    #   shuffle: false
    #   visualization:
    #     save_imgs: true
    #     plot_signals: true
    #     plot_signal_stats: true




# ==============================================================================
# real_unoccl_val_whitesilhouette FRAME 100
# ==============================================================================
    real_unoccl_val_whitesilhouette_frame100_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_unoccl_val_whitesilhouette_frame100}
      query_scheme: gradual_rot
      shuffle: false
    # real_unoccl_val_whitesilhouette_frame100_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_val_whitesilhouette_frame100}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_unoccl_val_whitesilhouette_frame100_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_val_whitesilhouette_frame100}
    #   query_scheme: gradual_depth
    #   shuffle: false






# ==============================================================================
# real_unoccl_val FRAME 100
# ==============================================================================
    real_unoccl_val_frame100_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_unoccl_val_frame100}
      query_scheme: gradual_rot
      shuffle: false
    # real_unoccl_val_frame100_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_val_frame100}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_unoccl_val_frame100_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_val_frame100}
    #   query_scheme: gradual_depth
    #   shuffle: false






# ==============================================================================
# real_occl_val FRAME 100
# ==============================================================================
    real_occl_val_frame100_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_occl_val_frame100}
      query_scheme: gradual_rot
      shuffle: false
    # real_occl_val_frame100_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_frame100}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_occl_val_frame100_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_frame100}
    #   query_scheme: gradual_depth
    #   shuffle: false


# ==============================================================================
# real_occl_val FRAME 228
# ==============================================================================
    real_occl_val_frame228_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_occl_val_frame228}
      query_scheme: gradual_rot
      shuffle: false
    # real_occl_val_frame228_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_frame228}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_occl_val_frame228_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_frame228}
    #   query_scheme: gradual_depth
    #   shuffle: false


# ==============================================================================
# real_occl_val FRAME 327
# ==============================================================================
    real_occl_val_frame327_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_occl_val_frame327}
      query_scheme: gradual_rot
      shuffle: false
    # real_occl_val_frame327_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_frame327}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_occl_val_frame327_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val_frame327}
    #   query_scheme: gradual_depth
    #   shuffle: false






# ==============================================================================
# real_occl_test FRAME 109
# ==============================================================================
    real_occl_test_frame109_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_occl_test_frame109}
      query_scheme: gradual_rot
      shuffle: false
    # real_occl_test_frame109_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_test_frame109}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_occl_test_frame109_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_test_frame109}
    #   query_scheme: gradual_depth
    #   shuffle: false


# ==============================================================================
# real_occl_test FRAME 112
# ==============================================================================
    real_occl_test_frame112_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_occl_test_frame112}
      query_scheme: gradual_rot
      shuffle: false
    # real_occl_test_frame112_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_test_frame112}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_occl_test_frame112_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_test_frame112}
    #   query_scheme: gradual_depth
    #   shuffle: false


# ==============================================================================
# real_occl_test FRAME 159
# ==============================================================================
    real_occl_test_frame159_gradual_rot:
      ref_schemeset:
        - {ref_scheme: real_occl_test_frame159}
      query_scheme: gradual_rot
      shuffle: false
    # real_occl_test_frame159_gradual_transl:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_test_frame159}
    #   query_scheme: gradual_transl
    #   shuffle: false

    # real_occl_test_frame159_gradual_depth:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_test_frame159}
    #   query_scheme: gradual_depth
    #   shuffle: false






    # real_unoccl_duck_gradual_rot:
    #   ref_schemeset:
    #     - {ref_scheme: real_unoccl_duck}
    #   query_scheme: gradual_rot
    #   shuffle: false

    # real_occl_val_gradual_rot:
    #   ref_schemeset:
    #     - {ref_scheme: real_occl_val}
    #   query_scheme: gradual_rot
    #   shuffle: false

    # synth_gradual_rot:
    #   ref_schemeset:
    #     - {ref_scheme: synth_default}
    #   query_scheme: gradual_rot
    #   shuffle: false
