default_schemeset_opts:
  test:
    # loading:
    #   # nbr_batches: 1
    #   # batch_size: 1
    #   nbr_batches: 3
    #   batch_size: 32
    #   # shuffle: fixed
    #   # shuffle: true
    #   shuffle: false
    #   coupled_ref_and_query_scheme_sampling: false
    # poseopt:
    #   enabled: false

    loading:
      nbr_batches: null # ignored
      # batch_size: 1
      batch_size: 10
      shuffle: fixed
      # shuffle: true
      # shuffle: false
      coupled_ref_and_query_scheme_sampling: false
    poseopt:
      enabled: true
      mode: optimize_all
      # mode: optimize_one_frame
      # mode: eval_init
      # mode: evaluate_and_plot_one_frame
    visualization:
      save_imgs: true
      plot_signals: false
      plot_signal_stats: false
    data:
      pushopt: false
      pushopt_prob: None
      min_dist_obj_and_camera: 100. # Minimum 10 cm between object surface and camera center
      max_nbr_resamplings: 100
data_sampling_scheme_defs:
  test:
    posesearch:
      query_schemeset: # NOTE: should ideally be disabled / not required during pose search
        # - scheme_name: 20deg_std
        - scheme_name: mild_gradual_rot
      opts:
        poseopt:
          enabled: true
